# -*- coding: utf-8 -*-
"""Named_Entity_Recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N9L-gT9l-CMS8xMtCLxDFX9a9yl9eAxD
"""

!pip install spacy

from google.colab import drive
drive.mount('/content/drive')

cd '/content/drive/MyDrive/ML/datasets'

"""NAMED ENTITY RECOGNITION

"""

import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp("Biden invites Ukrainian president to White House this summer")
print([(X.text, X.label_) for X in doc.ents])

"""SENTIMENT ANALYSIS

"""

import pandas as pd 
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer

df_data = pd.read_csv('avatar.csv', engine='python')
print(df_data.head())

df_data_lines = df_data.groupby('character').count()
df_data_lines = df_data_lines.sort_values(by=['character_words'], ascending=False)[:10]
top_character_names = df_data_lines.index.values
#print(top_character_names)

print("================")
#FILTER OUT NON TOP CHARACTERS 
df_character_sentiment = df_data[df_data['character'].isin(top_character_names)]
df_character_sentiment = df_character_sentiment[['character', 'character_words']]
#print(df_character_sentiment)

#SENTIMENT SCORE
s = SentimentIntensityAnalyzer()
df_character_sentiment.reset_index(inplace=True, drop=True)
df_character_sentiment[['neg', 'neu', 'pos', 'compound']] = df_character_sentiment['character_words'].apply(s.polarity_scores).apply(pd.Series)

print(df_character_sentiment.head())

"""WORDCLOUD"""

!pip install stylecloud

import stylecloud
show = stylecloud.gen_stylecloud(file_path='/content/drive/MyDrive/ML/datasets/Steve_Jobs_Speech.txt',
                          icon_name= "fas fa-apple-alt")

print(show)