# -*- coding: utf-8 -*-
"""CNN_Dog_Cat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OW5vq_Iveow8uKmjrvNClMPh6kT9DLgI
"""

from google.colab import drive
drive.mount('/content/drive')

cd '/content/drive/MyDrive/ML/datasets'

"""Part 1 - Data Preprocessing"""

#Preprocessing the Training set
#Do this to avoid overfitting - need to do transformations on images - Image Augementation - rescale and other transformations 
#Like fit_transfrom - training set

#Preprocessing the Test set
#Need to only rescale pixel - keep images intact - but rescale like training set
#Like transform - test set - to avoid information leakage from test set

"""Part 2 - Building the CNN"""

#Initialising the CNN

#Step 1 - Convolution
#Want to use Rectifer function for all layers except last layer 
#Connect to input layer

#Step 2 - Pooling

#Adding a second convolutional layer

#Step 3 - Flattening

#Step 4 - Full Connection
#For CV - need more units - 128

#Step 5 - Output Layer
#Doing Binary - only need 1 unit
#Activation function - sigmoid

"""Part 3 - Training the CNN"""

#Compiling the CNN

#Training the CNN on the Training set and evaluating it on the Test set

"""Part 4 - Making a single prediction"""

#Need to have image path, and the image size must be the same as training set image sizes
#Batch of Images